"""Add embedding to MenuItem

Revision ID: 727782b18963
Revises: 
Create Date: 2024-07-23 03:29:22.978755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727782b18963'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
